# Generated by Django 3.1.7 on 2021-03-26 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210318_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='updated_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
