# Generated by Django 3.1.7 on 2021-03-26 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210326_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
